### ISSUE TITLE
Class needs to be a trait to be mixed

### ISSUE THREAD

**Issue by novakov-alexey** [twilio/sbt-guardrail#11] opened 2019-03-14 21:35 UTC
It seems there is some issue. Not sure if it is a plugin bug or swagger definition problem.

There are class and companion object generated, but no trait. However, a generated code is mixing some trait in, which does not exist. 

```
target/scala-2.12/src_managed/main/swagger/definitions/ChannelCloseMutualTxJSON.scala:5:216: class ChannelCloseMutualTx needs to be a trait to be mixed in
[error] case class ChannelCloseMutualTxJSON(version: Long, channelId: String, fromId: String, initiatorAmountFinal: Long, responderAmountFinal: Long, ttl: Option[Long] = None, fee: Long, nonce: Long) extends GenericTx with ChannelCloseMutualTx
[error]
```

This swagger has been used to generate and compile client code: https://raw.githubusercontent.com/aeternity/aeternity/master/config/swagger.yaml

**Comment by blast-hardcheese** [comment] 2019-03-26 05:10
I wonder if this `allOf` with multiple objects is having problems because we represent parents as `class`, so attempting to describe multiple parents ends up with attempting to `with` a class definition, which scala does not permit.

If you have the time to pare down a limited reproducing test case, that would be appreciated; we can add a new test case with your minimal example, to prevent regression.

Also, if you wouldn't mind opening an issue in https://github.com/twilio/guardrail instead, that would be appreciated.

Thank you!

**Comment by novakov-alexey** [comment] 2019-03-26 08:00
Sure, I can open this issue in guardrail project too. Minimal example is basically a swagger yaml from my first message and then run `sbt compile`

**Comment by blast-hardcheese** [comment] 2019-03-26 21:05
Closing this ticket in favor of https://github.com/twilio/guardrail/issues/206

**Closed by blast-hardcheese** 2019-03-26 21:05 UTC
